name: flutter_portfolio
description: "UX design portfolio website"
publish_to: 'none' # Prevents accidental publication

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sizer:
  google_fonts:
  responsive_sizer:
  flutter_sticky_header:
  audioplayers:
  url_launcher:
  web_smooth_scroll:
  go_router: ^14.2.0
  url_strategy: ^0.3.0
  syncfusion_flutter_pdfviewer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Example for fonts (you can uncomment and edit as needed):
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
