name: Flutter CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Dart and Flutter
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # Adjust to your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Run analysis
        run: dart analyze

      # Build the Flutter web project
      - name: Build Flutter web
        run: flutter build web --release

      # Deploy to cyberwizard1001.github.io repository
      - name: Deploy to GitHub Pages repo
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: cyberwizard1001/cyberwizard1001.github.io
          TARGET_BRANCH: main
          TARGET_DIR: build/web
        run: |
          # Clone the target repository
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git target_repo
          cd target_repo

          # Remove all files from the target repository
          git rm -rf .

          # Copy the new build files into the target repository
          cp -r ../${TARGET_DIR}/* .

          # Commit and push the changes to the target repository
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy Flutter web app from ${GITHUB_REPOSITORY}@${GITHUB_SHA}"
          git push origin ${TARGET_BRANCH}
